
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 16 22:13:20 CST 2015
//----------------------------------------------------

package proyecto1_200915157;

/** CUP generated interface containing symbol constants. */
public interface simbolos {
  /* terminals */
  public static final int textop = 17;
  public static final int endDir = 6;
  public static final int texto = 18;
  public static final int errorlex = 2;
  public static final int con = 15;
  public static final int nom = 11;
  public static final int car = 7;
  public static final int endDoc = 10;
  public static final int endF = 14;
  public static final int est = 3;
  public static final int EOF = 0;
  public static final int endCon = 16;
  public static final int dir = 5;
  public static final int endNom = 12;
  public static final int error = 1;
  public static final int endCar = 8;
  public static final int f = 13;
  public static final int endEst = 4;
  public static final int doc = 9;

  /* non terminals */
  static final int ESTRUCTURA = 2;
  static final int DOCUMENTO = 5;
  static final int CARPETA = 4;
  static final int INICIO = 1;
  static final int DIRECTORIO = 3;
  static final int START = 0;
}

