
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 17 17:45:57 CST 2015
//----------------------------------------------------

package proyecto1_200915157;

/** CUP generated interface containing symbol constants. */
public interface SymConfig {
  /* terminals */
  public static final int errorlex = 2;
  public static final int error = 1;
  public static final int identificador = 3;
  public static final int EOF = 0;

  /* non terminals */
  static final int ESTRUCTURA = 2;
  static final int INICIO = 1;
  static final int START = 0;
}

